* Perju Stream Toolbox
Es un conjunto de herramientas para facilitar y hacer mas dinámicas las
emisiones en directo (streaming), empezando por un controlador para =OBS= y mas
adelante se añadirán otras funcionalidades.

** Se añade /tauri/ para publicar como aplicación de escritorio
/TODO revisar si es necesario con la githubaction/
para evitar el error del strip al compilar, se puede deshabilitar la opción
strip con ~NO_STRIP=true %comando%~

** Entornos de angular
Se ha creado la configuración de entornos para Angular y aparte de los dos
entornos básicos =Desarrollo= y =Produccion= se han añadido otros dos entornos mas.

- Desktop :: Entorno para compilar la aplicación de escritorio y que utilice el
  back creado en Rust.
- Obsweb :: Entorno creado para exportar solo el modulo del controlador de obs
  como una aplicación web.

* Documentación de desarrollo :dev:
** Gestión de ramas
- master :: la principal.
- release :: para publicar versiones.
- develop :: para ir probando los nuevos desarrollos.
** Como subir de versión
- Actualizar el número de versión en los archivos
  - ~./src-tauri/tauri.conf.json~
  - ~./src-tauri/Cargo.toml~
  - ~./package.json~
- Fusionar "=master=" en =release=
